language: ruby
cache:
  - bundler
services:
  - postgresql
before_install:
  - nvm install --lts
before_script:
  - bundle exec rails db:create
  - bundle exec rails db:schema:load
script:
  - bundle exec rspec
