language: ruby
rvm:
  — 2.6.3
cache:
  - bundler
services:
  - postgresql
before_script:
  - psql -c 'create database json_api_resources_test;' -U postgres
  - bundle exec rails db:migrate
script:
  - bundle exec rspec
